theme: jekyll-theme-cayman
title: Spring Boot Chaos Monkey
author: Benjamin Wilms
description: This project provides a Spring Boot Chaos Monkey and will try to attack your running Spring Boot App.
twitter:
  username: MrBWilms
social:
  name: Benjamin Wilms
  links:
    - https://twitter.com/MrBWilms
    - https://www.codecentric.de/team/benjamin-wilms/
    - https://github.com/MrBW
    - https://www.xing.com/profile/Benjamin_Wilms
