name: Publish Release

on:
  push:
    tags:
      - v*


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven deploy
        run: ./mvnw deploy -DperformRelease=true --settings .settings.xml
        env:
          SONATYPE_USERTOKEN: ${{ secrets.SONATYPE_USERTOKEN }}
          SONATYPE_USERTOKENPASSWORD: ${{ secrets.SONATYPE_USERTOKENPASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./chaos-monkey-docs/target/generated-docs
          destination_dir: latest
          commit_message: ${{ github.event.head_commit.message }}
